---
sudo: required
language: python
python:
  - "2.7"
services:
  - docker
before_install:
  - docker pull victorock/ansible-network:latest
script:
  - docker run --privileged --volume=/var/lib/docker --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro --volume="$PWD":/ansible:rw --name $timestamp  victorock/ansible-network:latest molecule test
