---
sudo: false
language: python
python:
  - "2.7"
services:
  - docker
before_install:
  - sudo apt-get -qq update
install:
  - pip install pip --upgrade
  - pip install ansible molecule boto boto3 --upgrade
script:
  - molecule test
