---
sudo: required
language: python
python:
  - "2.7"
services:
  - docker
before_install:
  - sudo apt-get -qq update
install:
  - pip install ansible molecule boto boto3 passlib ncclient netaddr xmltodict --upgrade
script:
  - molecule test --all
