---
- name: Prepare
  hosts: all
  gather_facts: false

  tasks:
    - name: "validate version"
      ios_command:
        commands: "show version"
        wait_for: "result[0] contains IOS"
        retries: 20
        interval: 5

    - name: "gather facts"
      ios_facts:
